version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    # https://matsuand.github.io/docs.docker.jp.onthefly/storage/volumes/
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    # https://docs.docker.jp/v19.03/config/container/start-containers-automatically.html
    restart: always
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - .:/myapp
      - gem_data:/usr/local/bundle # インストールしたGemファイルを永続化するための設定
    ports:
      - "3000:3000"
    restart: always
    tty: true # 疑似ターミナル (pseudo-TTY) を割り当て。
    stdin_open: true # サービス コンテナに標準入力を割り当てて実行するよう設定
    depends_on:
      - db
volumes:
  postgres_volume:
  gem_data:
